Module bomap2
    '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
    ' CICS Client Visual Basic constant file for bomap2.bms
    '
    ' Generated by CICS BMS Conversion Utility - Version 1.0
    ' This file can be loaded into a code module

    ' MAP2Map constants
    Public Const MAP2 = "0.40.0.24.40.80.107.268.284.292.424.438.443.515.518.523.595.598.603.675.678.683.755.758.763.901.918.1067.1078.1158.1238.1318.1322.1467.1476.1480.1482.1486.1488.1628.1708.1788"
    Public Const MAP2_TITLE = 24
    Public Const MAP2_INVNUM = 284
    Public Const MAP2_PROD11 = 438
    Public Const MAP2_PROD12 = 443
    Public Const MAP2_PROD21 = 518
    Public Const MAP2_PROD22 = 523
    Public Const MAP2_PROD31 = 598
    Public Const MAP2_PROD32 = 603
    Public Const MAP2_PROD41 = 678
    Public Const MAP2_PROD42 = 683
    Public Const MAP2_PROD51 = 758
    Public Const MAP2_PROD52 = 763
    Public Const MAP2_NAME = 918
    Public Const MAP2_ADDLN1 = 1078
    Public Const MAP2_ADDLN2 = 1158
    Public Const MAP2_ADDLN3 = 1238
    Public Const MAP2_POSTAL1 = 1318
    Public Const MAP2_POSTAL2 = 1322
    Public Const MAP2_ARCODE = 1476
    Public Const MAP2_EXCHNO = 1482
    Public Const MAP2_PHONNUM = 1488
    Public Const MAP2_MSG = 1788


End Module
